name: Run changeset

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - ".changeset/**.md"

jobs:
  run-changeset:
    name: Run changeset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://npm.pkg.github.com'

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Rollup
        run: pnpm run ci:packages:rollup

      - name: Authenticate with GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Run changeset
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish --registry=https://npm.pkg.github.com
          commit: 'chore(packages): version packages'
          title: 'chore(packages): version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}